spring:
  datasource:
    url:              jdbc:mysql://localhost:3306/{schema}
    driverClassName:  com.mysql.jdbc.Driver
    username:         {username}
    password:         {password}
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true